programs:
  - name: robinhood-markets-bounty
    platform: hackerone
    in_scope:
      - "*.rhinternal.net"
      - "*.robinhood.com"
      - "*.robinhood.net"
      - "*.say.rocks"
      - "*.saytechnologies.com"
      - "api.robinhood.com"
      - "cashier.robinhood.com"
      - "minerva.robinhood.com"
      - "nummus.robinhood.com"
      - "identi.robinhood.com"
      - "fusion.tradepmr.com"
      - "www.tradepmr.com"
      - "insight2.tradepmr.com"
      - "www.bitstamp.net"
      - "7671800.bitstamp.net"
      - "7671800.team.bitstamp.net"
      - "_16928ca3f53f40a48a751be40fa24e4c.bitstamp.net"
      - "_domainconnect.bitstamp.net"
      - "autodiscover.bitstamp.net"
      - "bounces.bitstamp.net"
      - "em1198.bitstamp.net"
      - "em4296.team.bitstamp.net"
      - "em9457.team.bitstamp.net"
      - "enterpriseenrollment.bitstamp.net"
      - "enterpriseregistration.bitstamp.net"
      - "status.bitstamp.net"
      - "url6884.team.bitstamp.net"
    out_of_scope:
      - "affiliates.robinhood.com"
      - "api-sandbox.tradepmr.com"
      - "api-validation.tradepmr.com"
      - "api.tradepmr.com"
      - "auth-sandbox.tradepmr.com"
      - "auth-validation.tradepmr.com"
      - "auth.tradepmr.com"
      - "careers.robinhood.com"
      - "content.research.robinhood.com"
      - "earlytalent.robinhood.com"
      - "esg.robinhood.com"
      - "events.robinhood.com"
      - "fleet.infra.robinhood.net"
      - "fusion-demo.tradepmr.com"
      - "fusion-demo.uat.tradepmr.com"
      - "fusion-demo.uat2.tradepmr.com"
      - "fusion.uat.tradepmr.com"
      - "fusion.uat2.tradepmr.com"
      - "fusion.uat3.tradepmr.com"
      - "go.robinhood.com"
      - "press.robinhood.com"
      - "roadshow.robinhood.com"
      - "sandbox.bitstamp.net"
      - "share.robinhood.com"
      - "shop.robinhood.com"
      - "startinvesting.robinhood.com"
      - "underthehoodpod.robinhood.com"
      - "vgs-api.robinhood.com"
      - "weareallinvestors.robinhood.com"
      - "www.saytechnologies.com"
    notes: "Imported from HackerOne scope CSV and Burp config export dated 2026-03-06; keep path-level exclusion for https://www.saytechnologies.com/contact/sales"
